/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as NewArticleRouteImport } from './routes/new-article'
import { Route as LexicalRouteImport } from './routes/lexical'
import { Route as GoldenRouteImport } from './routes/golden'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewArticleIdRouteImport } from './routes/review.$articleId'
import { Route as ReviewArticleIdIndexRouteImport } from './routes/review.$articleId.index'
import { Route as ReviewArticleIdValidatorRouteImport } from './routes/review.$articleId.validator'
import { Route as ReviewArticleIdSemanticRouteImport } from './routes/review.$articleId.semantic'
import { Route as ReviewArticleIdPreviewRouteImport } from './routes/review.$articleId.preview'
import { Route as ReviewArticleIdPhasesRouteImport } from './routes/review.$articleId.phases'
import { Route as ReviewArticleIdLlmPacketRouteImport } from './routes/review.$articleId.llm-packet'
import { Route as ReviewArticleIdGraphRouteImport } from './routes/review.$articleId.graph'
import { Route as ReviewArticleIdEvaluationRouteImport } from './routes/review.$articleId.evaluation'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArticleRoute = NewArticleRouteImport.update({
  id: '/new-article',
  path: '/new-article',
  getParentRoute: () => rootRouteImport,
} as any)
const LexicalRoute = LexicalRouteImport.update({
  id: '/lexical',
  path: '/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldenRoute = GoldenRouteImport.update({
  id: '/golden',
  path: '/golden',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewArticleIdRoute = ReviewArticleIdRouteImport.update({
  id: '/review/$articleId',
  path: '/review/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewArticleIdIndexRoute = ReviewArticleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewArticleIdRoute,
} as any)
const ReviewArticleIdValidatorRoute =
  ReviewArticleIdValidatorRouteImport.update({
    id: '/validator',
    path: '/validator',
    getParentRoute: () => ReviewArticleIdRoute,
  } as any)
const ReviewArticleIdSemanticRoute = ReviewArticleIdSemanticRouteImport.update({
  id: '/semantic',
  path: '/semantic',
  getParentRoute: () => ReviewArticleIdRoute,
} as any)
const ReviewArticleIdPreviewRoute = ReviewArticleIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ReviewArticleIdRoute,
} as any)
const ReviewArticleIdPhasesRoute = ReviewArticleIdPhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => ReviewArticleIdRoute,
} as any)
const ReviewArticleIdLlmPacketRoute =
  ReviewArticleIdLlmPacketRouteImport.update({
    id: '/llm-packet',
    path: '/llm-packet',
    getParentRoute: () => ReviewArticleIdRoute,
  } as any)
const ReviewArticleIdGraphRoute = ReviewArticleIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ReviewArticleIdRoute,
} as any)
const ReviewArticleIdEvaluationRoute =
  ReviewArticleIdEvaluationRouteImport.update({
    id: '/evaluation',
    path: '/evaluation',
    getParentRoute: () => ReviewArticleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/entities': typeof EntitiesRoute
  '/golden': typeof GoldenRoute
  '/lexical': typeof LexicalRoute
  '/new-article': typeof NewArticleRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/review/$articleId': typeof ReviewArticleIdRouteWithChildren
  '/review/$articleId/evaluation': typeof ReviewArticleIdEvaluationRoute
  '/review/$articleId/graph': typeof ReviewArticleIdGraphRoute
  '/review/$articleId/llm-packet': typeof ReviewArticleIdLlmPacketRoute
  '/review/$articleId/phases': typeof ReviewArticleIdPhasesRoute
  '/review/$articleId/preview': typeof ReviewArticleIdPreviewRoute
  '/review/$articleId/semantic': typeof ReviewArticleIdSemanticRoute
  '/review/$articleId/validator': typeof ReviewArticleIdValidatorRoute
  '/review/$articleId/': typeof ReviewArticleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/entities': typeof EntitiesRoute
  '/golden': typeof GoldenRoute
  '/lexical': typeof LexicalRoute
  '/new-article': typeof NewArticleRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/review/$articleId/evaluation': typeof ReviewArticleIdEvaluationRoute
  '/review/$articleId/graph': typeof ReviewArticleIdGraphRoute
  '/review/$articleId/llm-packet': typeof ReviewArticleIdLlmPacketRoute
  '/review/$articleId/phases': typeof ReviewArticleIdPhasesRoute
  '/review/$articleId/preview': typeof ReviewArticleIdPreviewRoute
  '/review/$articleId/semantic': typeof ReviewArticleIdSemanticRoute
  '/review/$articleId/validator': typeof ReviewArticleIdValidatorRoute
  '/review/$articleId': typeof ReviewArticleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/entities': typeof EntitiesRoute
  '/golden': typeof GoldenRoute
  '/lexical': typeof LexicalRoute
  '/new-article': typeof NewArticleRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/review/$articleId': typeof ReviewArticleIdRouteWithChildren
  '/review/$articleId/evaluation': typeof ReviewArticleIdEvaluationRoute
  '/review/$articleId/graph': typeof ReviewArticleIdGraphRoute
  '/review/$articleId/llm-packet': typeof ReviewArticleIdLlmPacketRoute
  '/review/$articleId/phases': typeof ReviewArticleIdPhasesRoute
  '/review/$articleId/preview': typeof ReviewArticleIdPreviewRoute
  '/review/$articleId/semantic': typeof ReviewArticleIdSemanticRoute
  '/review/$articleId/validator': typeof ReviewArticleIdValidatorRoute
  '/review/$articleId/': typeof ReviewArticleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/entities'
    | '/golden'
    | '/lexical'
    | '/new-article'
    | '/rules'
    | '/settings'
    | '/review/$articleId'
    | '/review/$articleId/evaluation'
    | '/review/$articleId/graph'
    | '/review/$articleId/llm-packet'
    | '/review/$articleId/phases'
    | '/review/$articleId/preview'
    | '/review/$articleId/semantic'
    | '/review/$articleId/validator'
    | '/review/$articleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/entities'
    | '/golden'
    | '/lexical'
    | '/new-article'
    | '/rules'
    | '/settings'
    | '/review/$articleId/evaluation'
    | '/review/$articleId/graph'
    | '/review/$articleId/llm-packet'
    | '/review/$articleId/phases'
    | '/review/$articleId/preview'
    | '/review/$articleId/semantic'
    | '/review/$articleId/validator'
    | '/review/$articleId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/entities'
    | '/golden'
    | '/lexical'
    | '/new-article'
    | '/rules'
    | '/settings'
    | '/review/$articleId'
    | '/review/$articleId/evaluation'
    | '/review/$articleId/graph'
    | '/review/$articleId/llm-packet'
    | '/review/$articleId/phases'
    | '/review/$articleId/preview'
    | '/review/$articleId/semantic'
    | '/review/$articleId/validator'
    | '/review/$articleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  EntitiesRoute: typeof EntitiesRoute
  GoldenRoute: typeof GoldenRoute
  LexicalRoute: typeof LexicalRoute
  NewArticleRoute: typeof NewArticleRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  ReviewArticleIdRoute: typeof ReviewArticleIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-article': {
      id: '/new-article'
      path: '/new-article'
      fullPath: '/new-article'
      preLoaderRoute: typeof NewArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexical': {
      id: '/lexical'
      path: '/lexical'
      fullPath: '/lexical'
      preLoaderRoute: typeof LexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golden': {
      id: '/golden'
      path: '/golden'
      fullPath: '/golden'
      preLoaderRoute: typeof GoldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$articleId': {
      id: '/review/$articleId'
      path: '/review/$articleId'
      fullPath: '/review/$articleId'
      preLoaderRoute: typeof ReviewArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$articleId/': {
      id: '/review/$articleId/'
      path: '/'
      fullPath: '/review/$articleId/'
      preLoaderRoute: typeof ReviewArticleIdIndexRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
    '/review/$articleId/validator': {
      id: '/review/$articleId/validator'
      path: '/validator'
      fullPath: '/review/$articleId/validator'
      preLoaderRoute: typeof ReviewArticleIdValidatorRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
    '/review/$articleId/semantic': {
      id: '/review/$articleId/semantic'
      path: '/semantic'
      fullPath: '/review/$articleId/semantic'
      preLoaderRoute: typeof ReviewArticleIdSemanticRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
    '/review/$articleId/preview': {
      id: '/review/$articleId/preview'
      path: '/preview'
      fullPath: '/review/$articleId/preview'
      preLoaderRoute: typeof ReviewArticleIdPreviewRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
    '/review/$articleId/phases': {
      id: '/review/$articleId/phases'
      path: '/phases'
      fullPath: '/review/$articleId/phases'
      preLoaderRoute: typeof ReviewArticleIdPhasesRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
    '/review/$articleId/llm-packet': {
      id: '/review/$articleId/llm-packet'
      path: '/llm-packet'
      fullPath: '/review/$articleId/llm-packet'
      preLoaderRoute: typeof ReviewArticleIdLlmPacketRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
    '/review/$articleId/graph': {
      id: '/review/$articleId/graph'
      path: '/graph'
      fullPath: '/review/$articleId/graph'
      preLoaderRoute: typeof ReviewArticleIdGraphRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
    '/review/$articleId/evaluation': {
      id: '/review/$articleId/evaluation'
      path: '/evaluation'
      fullPath: '/review/$articleId/evaluation'
      preLoaderRoute: typeof ReviewArticleIdEvaluationRouteImport
      parentRoute: typeof ReviewArticleIdRoute
    }
  }
}

interface ReviewArticleIdRouteChildren {
  ReviewArticleIdEvaluationRoute: typeof ReviewArticleIdEvaluationRoute
  ReviewArticleIdGraphRoute: typeof ReviewArticleIdGraphRoute
  ReviewArticleIdLlmPacketRoute: typeof ReviewArticleIdLlmPacketRoute
  ReviewArticleIdPhasesRoute: typeof ReviewArticleIdPhasesRoute
  ReviewArticleIdPreviewRoute: typeof ReviewArticleIdPreviewRoute
  ReviewArticleIdSemanticRoute: typeof ReviewArticleIdSemanticRoute
  ReviewArticleIdValidatorRoute: typeof ReviewArticleIdValidatorRoute
  ReviewArticleIdIndexRoute: typeof ReviewArticleIdIndexRoute
}

const ReviewArticleIdRouteChildren: ReviewArticleIdRouteChildren = {
  ReviewArticleIdEvaluationRoute: ReviewArticleIdEvaluationRoute,
  ReviewArticleIdGraphRoute: ReviewArticleIdGraphRoute,
  ReviewArticleIdLlmPacketRoute: ReviewArticleIdLlmPacketRoute,
  ReviewArticleIdPhasesRoute: ReviewArticleIdPhasesRoute,
  ReviewArticleIdPreviewRoute: ReviewArticleIdPreviewRoute,
  ReviewArticleIdSemanticRoute: ReviewArticleIdSemanticRoute,
  ReviewArticleIdValidatorRoute: ReviewArticleIdValidatorRoute,
  ReviewArticleIdIndexRoute: ReviewArticleIdIndexRoute,
}

const ReviewArticleIdRouteWithChildren = ReviewArticleIdRoute._addFileChildren(
  ReviewArticleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  EntitiesRoute: EntitiesRoute,
  GoldenRoute: GoldenRoute,
  LexicalRoute: LexicalRoute,
  NewArticleRoute: NewArticleRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  ReviewArticleIdRoute: ReviewArticleIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
